---
- name: Gather package facts.
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.userspace_bits == '32'
  tags: [ "always" ]

- name: Synchronize dc directory.
  ansible.posix.synchronize:
    src: dc
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Copy templated dc files into place.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/docker-obs/{{ item.dest }}"
    mode: 0644
  loop:
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
  notify: Restart docker-obs
  become: false

- name: Start the different services in docker-obs (rebuild if necessary)
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/docker-obs/"
    build: true
  become: false
