---
- name: restart dc
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/dc/"
    build: false
    restarted: true
  become: false

- name: stop dc
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/dc/"
    build: false
    restarted: true
  become: false
